# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Development Site settings
title: Alkami
email: info@alkami.io
description: > # this means to ignore newlines until "baseurl:"
  Alkami is a group of entrepreneurs that happen to be passionate web-developers. Many of us are based in Denver Colorado. We design and build applications for the web.
baseurl: "/alkami-web-site-blog" # the subpath of your site, e.g. /blog
url: "http://alkamicode.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  AlkamiCode
facebook_username: alkami.io
linkedin_username: company/alkami

# Build settings
markdown: kramdown
