# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Production Site settings
title: Alkami - Web Development, Web Design, Apps, Web Sites
email: info@alkami.io
description: > # this means to ignore newlines until "baseurl:"
  Alkami is a group of entrepreneurs that happen to be passionate web site and web application developers. Many of us are based in Denver Colorado. We partner with small business and entrepreneurs to help design and build apps for the web. We build everything from e-commerce platforms, blogs, social networking apps, marketing sites to custom in house sofware for small business.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alkami.io" # the base hostname & protocol for your site
permalink: /:title
post_dirs: false
twitter_username:
github_username:  AlkamiCode
facebook_username: alkami.io
linkedin_username: company/alkami

# Build settings
markdown: kramdown
